story6/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from story6app import urls as web
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('',include(web))
]

story6app/urls.py
from django.urls import path
from .views import index
from .views import profile
from .views import books
from .views import books_data
from .views import subscribers
from .views import save_subscribers
from .views import show_subscribers
from .views import delete_subscribers

app_name = 'story6app'
urlpatterns = [
    path('story6/',index,name='index'),
    path('profile/',profile,name='profile'),
    path('books/',books,name='books'),
    path('books/books_data/<str:tema>/',books_data,name='books'),
    path('subscribers/', subscribers, name='subscribers'),
    path('Save_Subscribers/',save_subscribers, name='Save_Subscribers'),
    path('Show_Subscribers/',show_subscribers,name='Show_Subscribers'),
    path('Delete_Subscribers/',delete_subscribers,name="Delete_Subscribers")
]

story6app/models.py
from django.db import models

# Create your models here.
class MyForm(models.Model):
    status = models.CharField(max_length=300)
    time = models.DateTimeField(auto_now_add=True)

class SubscriberModels(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True, db_index=True)
    password = models.CharField(max_length=15)

story6app/forms.py
from django import forms
from datetime import datetime

class StatusForm(forms.Form):
    error_messages={
        'required':'This field is required.',
    }
    stat_attrs={
        'type':'text',
        'class':'form-control',
        'placeholder':'How are you doing today?',
        'id':'form-forms.py'
    }
    status=forms.CharField(
        label="Status", 
        max_length=300,
        required=True,
        widget=forms.TextInput(attrs=stat_attrs))

class SubscriberForms(forms.Form):
    error_messages={
        'required':'Required Field'
    }
    name_attrs={
        'type':'text',
        'class':'form-control',
        'placeholder': 'Required'
    }
    email_attrs={
        'type':'email',
        'class': 'form-control',
        'placeholder':'Required'
    }
    password_attrs={
        'type':'password',
        'class':'form-control',
        'placeholder':'Required'
    }

    name = forms.CharField(
        label='Name',
        required = True, 
        widget=forms.TextInput(attrs=name_attrs)
    )

    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=30,
        widget=forms.EmailInput(attrs=email_attrs)
    )

    password = forms.CharField(
        label='Password',
        required=True,
        widget=forms.PasswordInput(attrs=password_attrs)
    )

story6app/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.http import HttpResponse
from django.http import JsonResponse
from django.db import IntegrityError
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt

import urllib.request, json
import requests

from .forms import StatusForm
from .forms import SubscriberForms
from .models import MyForm
from .models import SubscriberModels
from datetime import datetime,date

name = "Laila Saffanah"
major = "Computer Information System"
univ = "Universitas Indonesia"
bio = "Blood Type: A, Scorpio, INFJ-T"
likes = "Love organizing, Cartoon concept enthusiast, Dystopian enthusiast" 

activities= "Majoring in computer science, my daily activity is coding. I haven't read books again lately, eventough it's one of my hobbies. Currently, i'm only able to read poem books such as nikita gill's and rupi kaur books. "
organizations = "Currently i'm officiates in BEM Fasilkom UI department Pengabdian Masyarakat. I'm also a staff of SIWAKNG in event division. I learn many things from joining organizations. Example: Time management"
achievements = "I have few achievements in life. Passing the SBMPTN is one of it. Another one is second lineup in School's Batik Design Competition in SMAN 78 Jakarta Barat"

response={}

def profile(request):
    response={'name':name,'major':major,'univ':univ,'bio':bio,'likes':likes,'activities':activities,'achievements':achievements,'organizations':organizations}
    return render(request,'profile.html',response)
    
def index(request):
    response['formlist'] = StatusForm
    allFormObj = MyForm.objects.all()
    response['StatusForm'] = allFormObj

    form = StatusForm(request.POST or None)
    if(request.method=='POST' and form.is_valid()):
        response['status'] = request.POST['status']
        allForms = MyForm(status=response['status'])
        allForms.save()
        return render(request,'landing_page.html',response)
    else:
        return render(request,'landing_page.html',response)

def books_data(request,tema):
    raw = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + tema).json()
    items=[]
    for subdata in raw['items']:
        data={}
        data['thumbnail'] = subdata['volumeInfo']['imageLinks']['thumbnail'] if 'imageLinks' in subdata['volumeInfo'].keys() else 'Tidak ada'
        data['title'] = subdata['volumeInfo']['title'] 
        data['authors']=", ".join(subdata['volumeInfo']['authors']) if 'authors' in subdata['volumeInfo'].keys() else 'Tidak ada'
        data['publishedDate']= subdata['volumeInfo']['publishedDate'] if 'publishedDate' in subdata['volumeInfo'].keys() else 'Tidak ada'  
        items.append(data)
    return JsonResponse({"data":items})

def books(request):
    html='books.html'
    return render(request,html)

def subscribers(request):
    form = SubscriberForms(request.POST)
    html = 'subscribers.html'
    return render(request,html,{'form':form})

def save_subscribers(request):
    response['form'] = SubscriberForms()
    form = SubscriberForms(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        response['name'] = request.POST['name']
        response['email'] = request.POST['email']
        response['password'] = request.POST['password']
        status = 'True'
        #Store account into subscribers database
        try:
            storedata = SubscriberModels(
            name=response['name'],
            email=response['email'],
            password=response['password']
            )
            storedata.save()
            return JsonResponse({'status':status})
        except IntegrityError as e:
            status = 'False'
            return JsonResponse({'status':status})        
    status = 'False'
    return JsonResponse({'status':status})

def show_subscribers(request):
    data = list( SubscriberModels.objects.all().values('pk','name','email','password'))
    return JsonResponse({'subsdata':data})
    
@csrf_exempt
def delete_subscribers(request):
    if(request.method == 'POST'):
        subsdata = request.POST['pk']
        SubscriberModels.objects.filter(pk=subsdata).delete()
        return HttpResponse({'status':'Success'})
    else:
        return HttpResponse({'status':'Failed to load page'})

story6app/templates/books.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Saffa's Books</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/books_styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/books_scripts.js' %}"></script>
</head>
<header>
    {% include "partials/navbar.html" %}
</header>
<body>
    <h3 id='header'>Literature Corner</h3>
    <br>
    <center>
        <div class='buttons'>
            <button type="button" class="btn btn-outline-primary" id="quilting">Quilting</button>
            <button type="button" class="btn btn-outline-secondary" id="architecture">Architecture</button>
            <button type="button" class="btn btn-outline-success" id="comic">Comic</button>
        </div>
    </center>
    <br>
    <div class='counter-block'>
        <i class='fa fa-adjust'></i> My Favorites: <span class="counter">0</span>
    </div>
    <br>
    <center>
        <table class="table" id='book-table'>
            <tr>
                <thead>
                    <th scope="col">No</th>
                    <th scope="col">Cover</th>
                    <th scope="col">Title</th>
                    <th scope="col">Authors</th>
                    <th scope="col">Published <br></th>
                    <th scope="col">Favorites</th>
                </thead>
            </tr>
            <tbody></tbody>
        </table>
    </center>
</body>
</html>

story6app/templates/landing_page.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Saffa's Status</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/bootstrap-responsive.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/status_styles.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/profile_script.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min. css" rel="stylesheet" /> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js "></script>
</head>
<header>
    {% include "partials/navbar.html" %}
</header>
<body class="class-body" id="id-body">
    <div class="container" id="formtainer">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="center-text" id="hello-text">Hello, Apa kabar?</h1>
            </div>
        </div>
        <div class =row>

            <form id="form" action="{% url 'story6app:index' %}" method="POST">
                {% csrf_token %}
                {% for field in formlist %}
                    {{ field.label_tag }}
                    <br>
                    {{ field }}
                {% endfor %}
                <br>
                <button type="submit" id="submit-button" class="btn btn-progress">Submit</button>
            </form>
            
        </div>
        <div class="container">
            <br>
            {% for result in StatusForm %}
                <div class="col-sm-4" id="result-status">
                    <h5>Date: {{result.time}}</h5>
                    <h5>Status: {{result.status}}</h5>
                </div>
            {% endfor %}
        </div>
    </div>
    <br>    
</body>
</html>

story6app/templates/partials/navbar.html
<nav class="navbar navbar-default">
        <div class="container-fluid">
        <div class="navbar-header">
        <a class="navbar-brand" href="#"><img src="https://scontent.fcgk9-1.fna.fbcdn.net/v/t1.0-9/41962049_2629656550381489_4542339905962901504_n.jpg?_nc_cat=0&_nc_eui2=AeH4W8PBR4elwge7dKKZygqKY-5MAyUZe2m7bgK2TR45aY-CIcfjIDrtKz8e3ZZcJx4aWEOha7OXL5a10rJVhWJb6z2gf70EvwKI-Q02ACn9Ww&oh=9eed4f8608b076041b1c8e7c72f0c597&oe=5C346180"
            width="35" height="35"></a>
        </div>
            <ul class="nav navbar-nav navbar-right">
            <li><a href="../story6">Status Form</a></li>
            <li><a href="../profile">Profile</a></li>
            <li><a href="../books">My Library</a></li>
            <li><a href="../subscribers">Subscribe Me</a></li>
            <li><a id="theme-button">Change Theme</a></li>
            <form class="navbar-form navbar-left" action="/action_page.php">
            <div class="form-group" id="form-group-nav">
            <input type="text" class="form-control" placeholder="Search here...">
            </div>
            <button type="submit" class="btn btn-default">Search</button>
            </form>
            </ul>
        </div>
</nav>

story6app/templates/profile.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Saffa's Profile</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/profile_styles.css' %}">
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{% static 'js/profile_script.js' %}"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min. css" rel="stylesheet" /> 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js "></script>
</head>
<header>
    {% include "partials/navbar.html" %}
</header>
<body onload="myFunction()">
    <div id="loader"></div>
    <div style="display: none;" id="myDiv" class="animate-bottom">
        <h1 id="hello" align="center">hello</h1>
        <h1 id="name" align="center">My name is {{ name }}</h1>
        <center>
        <article align="center" class="description">Currently majoring in {{ major }}</article>
        <article align="center" class="description">{{ univ }}</article>
        <article align="center" class="description">{{ bio }}</article>
        <article align="center" class="description">{{ likes }}<sx/article>
    
        <div>
            <br>
            <img data-toggle="tooltip" title="Ini foto saya" src="https://scontent.fcgk8-1.fna.fbcdn.net/v/t1.0-9/45607155_2729761520370991_1432876187448770560_n.jpg?_nc_cat=108&_nc_eui2=AeHuvU2GaN3IZDCIx3b86gGAn9FNpfMgX5Fzf06wIQMuUE23xg5siERGbKYI7sNjDulxpoyEOiyaDBTdEM9_xE7M_5IaHkeSsDVM6YbmIgTFKg&_nc_ht=scontent.fcgk8-1.fna&oh=85cfc00f274d1bdbbb289ab52211d3ec&oe=5C7C059C" align="center" alt="myphoto"
            id="profile-img">
        </div>
        
        <p align="center" id="acc-description">
            <br>My recent...<br>
        </p>
    
        <div class="accordions">
            <button class="accordion">Activities</button>
            <div class="panel">
                <p class="content">{{ activities }}</p>
            </div>
    
            <button class="accordion">Organizations</button>
            <div class="panel">
                <p class="content">{{ organizations }}</p>
            </div>
    
            <button class="accordion">Achievements</button>
            <div class="panel">
                <p class="content">{{ achievements }}</p>
            </div>
        </div>
        <br>
    </div>
    
</body>
</html>

story6app/templates/subscribers.html
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Subscriber Form</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel='stylesheet' href='https://use.fontawesome.com/releases/v5.5.0/css/all.css' integrity='sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU' crossorigin='anonymous'>
    <link rel="stylesheet" media="screen" type="text/css" href="{% static 'css/subscribers_styles.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript" src="{% static 'js/subscribers.js' %}"></script>
</head>
<header>
    {% include "partials/navbar.html" %}
</header>
<body>
    <br>
    <h4 align="center" id="header">like our content?</h4>
    <p align="center" id="header-description">Fill the form below to subscribe this website</p>
    <br>
    <div class="col-sm-4"></div>
    <div class="form-block col-sm-4">
        <div id="buat-alert"></div>
        <form class='form-group' id='subsform' method='POST' action="{% url 'story6app:Save_Subscribers' %}">
            <div>
                {% csrf_token %}
                {% for fields in form %}
                    {{ fields.label_tag }}
                    {{ fields }}
                {% endfor %}
            </div>
            <br>
            <div align="center">
                <button class='btn btn-default' id='subs-button' type="submit">Subscribe!</button>
            </div>
        </form>
        <br>
        <br>
        <h4 id='subslist' align="center">Our Subscribers</h4>
        <div id='list-subscriber'>
            <br>
            <center>
                <table class="table" id='subs-table'>
                    <tr>
                        <thead>
                            <th scope="col">No</th>
                            <th scope="col">Name</th>
                            <th scope="col">Email</th>
                            <th scope="col">Status</th>
                        </thead>
                    </tr>
                    <tbody></tbody>
                </table>
            </center>
        </div>
    </div>
    <div class="col-sm-4"></div>
</body>
</html>